name: 🐛 Ошибка в переводе
description: Сообщите об ошибке в переводе или документации
title: "[Ошибка] "
labels: ["bug"]
assignees: ["dadec666"]

body:
  - type: markdown
    attributes:
      value: |
        Спасибо за то, что помогаете улучшать качество перевода!

  - type: textarea
    id: description
    attributes:
      label: "Описание ошибки"
      description: "Опишите ошибку кратко и ясно"
      placeholder: "Например: Некорректный перевод термина 'exception' в главе 8"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: "Местоположение"
      description: "Укажите, где находится ошибка"
      placeholder: "Например: Глава 8, раздел 8.1, tutorial/errors.po строка 42"
    validations:
      required: true

  - type: textarea
    id: current_text
    attributes:
      label: "Текущий текст (неправильный)"
      description: "Приведите текущий некорректный перевод"
      placeholder: "Пример: 'Ошибка возникла в программе'"
    validations:
      required: true

  - type: textarea
    id: expected_text
    attributes:
      label: "Правильный текст"
      description: "Как должно быть правильно"
      placeholder: "Пример: 'Исключение возникло в программе'"
    validations:
      required: true

  - type: textarea
    id: reasoning
    attributes:
      label: "Обоснование"
      description: "Почему это ошибка? Ссылки на глоссарий или стандарты"
      placeholder: "Пример: В глоссарии exception переводится как 'исключение', а не 'ошибка'"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      description: "Насколько критична эта ошибка?"
      options:
        - "Низкий (опечатка, стиль)"
        - "Средний (неточность перевода)"
        - "Высокий (критическая ошибка или нарушение стандартов)"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Подтверждение"
      description: "Подтвердите перед отправкой"
      options:
        - label: "Я прочитал руководство по переводу и глоссарий"
          required: false
        - label: "Я проверил, что похожая ошибка еще не была сообщена"
          required: true