name: 📚 Перевод главы учебника
description: Задача по переводу конкретной главы
title: "[Глава ] "
labels: ["chapter", "translation", "tutorial"]
assignees: ["dadec666"]

body:
  - type: markdown
    attributes:
      value: |
        Используйте этот шаблон для координации работы над конкретной главой.

  - type: dropdown
    id: chapter_number
    attributes:
      label: "Номер главы"
      description: "Какую главу учебника надо перевести?"
      options:
        - "1. Whetting Your Appetite (Пробуждение аппетита)"
        - "2. Using the Python Interpreter (Использование интерпретатора)"
        - "3. An Informal Introduction to Python (Неформальное введение в Python)"
        - "4. More Control Flow Tools (Инструменты управления потоком)"
        - "5. Data Structures (Структуры данных)"
        - "6. Modules (Модули)"
        - "7. Input and Output (Ввод и вывод)"
        - "8. Errors and Exceptions (Ошибки и исключения)"
        - "9. Classes (Классы)"
        - "10. Brief Tour of the Standard Library (Обзор стандартной библиотеки)"
        - "11. Brief Tour Part II (Обзор стандартной библиотеки — Часть II)"
        - "12. Virtual Environments and Packages (Виртуальные окружения и пакеты)"
        - "13. What Now? (Что дальше?)"
    validations:
      required: true

  - type: checkboxes
    id: status
    attributes:
      label: "Прогресс перевода"
      description: "Отмечайте выполненные части"
      options:
        - label: "Первичный перевод всех строк"
        - label: "Проверка терминологии"
        - label: "Проверка примеров кода"
        - label: "Peer Review от других переводчиков"
        - label: "Финальная вычитка редакторов"
        - label: "Одобрение координаторов"

  - type: textarea
    id: assignees
    attributes:
      label: "Ответственные"
      description: "Кто работает над этой главой? (@упоминания GitHub)"
      placeholder: "Например: @username1 (основной переводчик), @username2 (редактор)"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: "Примечания"
      description: "Сложности, особенности или полезная информация"
      placeholder: |
        Например:
        - В этой главе много примеров кода с комментариями
        - Нуждается в согласовании термина "comprehension"
        - Связана с главой 4 (перекрестные ссылки)
    validations:
      required: false